### ISSUE TITLE
Are the flatbuffer schema and the autogenerated Rust code in sync?

### ISSUE THREAD

**Issue by elefthei** [QED-it/zkinterface#41]
I'm using the `zkinterface.fbs` schema to write/read files successfully, I can read the files I wrote back with `flatc` using

```
flatc -o outs ../zkinterface.fbs --json --strict-json -- foo.zkif
```

But I can't get the `zkif` rust application to read my files back. I was wondering if using the above command and the `zkif` rust
app are equivalent?

 It could be I'm using a newer version of `flatc` I am on 2.0. I am also unable to regenerate the rust code with
```cargo build --features fbs```

The generated rust code does not compile and I get a lot of errors.

**Comment by sga001** [comment]
To follow up, it looks as though the flatbuffer schema (zkinterface.fbs) and the rust code in src/zkinterface_generated.rs might either be out of sync, or maybe it is an issue with newer versions of `flatc` being unable to understand zkif outputs. I'm using  `flatc` 1.11.0 and I'm also seeing this issue.

For example, if I run

```flatc -o outs zkinterface.fbs --json --strict-json -- examples/example.zkif```

I get an error (here ``examples/example.zkif`` is the example provided in this repo).

**Comment by elefthei** [comment]
Here's what I think is happening
https://github.com/QED-it/zkinterface/blob/f3371d4c608f94f6c22330897afa14bcb4cf6d05/rust/src/structs/command.rs#L71

Is writing the binary data without the optional file identifier (magic-bytes), however the schema indicates that the identifier should be used.
```
// When storing messages to files, this extension and identifier should be used.
file_extension "zkif";
file_identifier "zkif"; // a.k.a. magic bytes.
```
Here's some more on file identifiers
From ["File identification and extension"](https://google.github.io/flatbuffers/flatbuffers_guide_writing_schema.html):

> Typically, a FlatBuffer binary buffer is not self-describing, i.e. it needs you to know its schema to parse it correctly. But if you want to use a FlatBuffer as a file format, it would be convenient to be able to have a "magic number" in there, like most file formats have, to be able to do a sanity check to see if you're reading the kind of file you're expecting.
> Now, you can always prefix a FlatBuffer with your own file header, but FlatBuffers has a built-in way to add an identifier to a FlatBuffer that takes up minimal space, and keeps the buffer compatible with buffers that don't have such an identifier.

Given the intention in `zkinterface.fbs` is to use the "zkif" magic bytes, I think https://github.com/QED-it/zkinterface/blob/f3371d4c608f94f6c22330897afa14bcb4cf6d05/rust/src/structs/command.rs#L71 should change to include the file identifier. I can make a separate issue for this if needed.

**Comment by elefthei** [comment]
FYI, I implemented the change described above and still, examples generated by `zkif` cannot be read back from `flatc`, as described by @sga001 . We don't know why and this is blocking us.

**Comment by Michael-Qedit** [comment]
> I'm using the `zkinterface.fbs` schema to write/read files successfully, I can read the files I wrote back with `flatc` using
>
> ```
> flatc -o outs ../zkinterface.fbs --json --strict-json -- foo.zkif
> ```
I did not know this feature, but it's good to know!

> But I can't get the `zkif` rust application to read my files back. I was wondering if using the above command and the `zkif` rust
> app are equivalent?
> 
> It could be I'm using a newer version of `flatc` 
Yes indeed, the FBS schema is compiled with `flatc v. 1.12.0`, which produced the `zkinterface_generated.rs` file. And `flatc v. 2.0` is currently not compatible.

> I am on 2.0. I am also unable to regenerate the rust code with
> `cargo build --features fbs`
> 
> The generated rust code does not compile and I get a lot of errors.
This is again because of incompatibilities between `flatc v 1.XX` and `flatc v. 2.XX`. Since the Rust code is constructed around what was generated from the `flatc` compiler, it cannot compile with something generated with incompatible versions.
Maybe we should upgrade `zkinterface` at some point to migrate to `flatc 2.0`.

if I run
```
flatc -o outs zkinterface.fbs --json --strict-json -- examples/example.zkif
```
I get an error too. But the error says 
```
flatc: error: binary "rust/example.zkif" does not have expected file_identifier "zkif", use --raw-binary to read this file anyway.
```
When adding this option, I get no error, but the output file is "empty". Only a single bracket pair `{}`, which is strange because no error means that the file is indeed compliant with the provided FBS schema.
_NB_:  in [Writing a Schema ](https://google.github.io/flatbuffers/flatbuffers_guide_writing_schema.html), it's said that 

> Now, you can always prefix a FlatBuffer with your own file header, but FlatBuffers has a built-in way to add an identifier to a FlatBuffer that takes up minimal space, and keeps the buffer compatible with buffers that don't have such an identifier.

It means that this file identifier is not mandatory.

Regarding the fix suggested by @elefthei, this is actually true, but this is incomplete. All the types in `Message` should be updated this way (that is `Command`, `ConstraintSystem`, `CircuitHeader`, `Witness`), but even if I update all of these, this does not fill the JSON file properly...
And I can see that these "magic bytes" are properly added to the binary file:
```
00000000  c4 00 00 00 14 00 00 00  7a 6b 69 66 00 00 00 00  |........zkif....|
00000010  08 00 0c 00 07 00 08 00  08 00 00 00 00 00 00 01  |................|
00000020  10 00 00 00 0c 00 18 00  04 00 10 00 08 00 0c 00  |................|
00000030  0c 00 00 00 5c 00 00 00  48 00 00 00 0c 00 00 00  |....\...H.......|
00000040  06 00 00 00 00 00 00 00  01 00 00 00 10 00 00 00  |................|
00000050  00 00 0a 00 0c 00 04 00  00 00 08 00 0a 00 00 00  |................|
00000060  14 00 00 00 04 00 00 00  07 00 00 00 65 78 61 6d  |............exam|
00000070  70 6c 65 00 04 00 00 00  4e 61 6d 65 00 00 00 00  |ple.....Name....|
```

I cannot tell for now if this is a bug on `zkinterface` or in `FlatBuffers/flatc`, and this requires more investigation. Maybe upgrading `zkinterface` to `flatc 2.0` would solve this issue?

**Comment by Michael-Qedit** [comment]
BTW, to answer the question initially raised in the subject of this thread, no, the uploaded files are not out-of-sync ;)

**Comment by elefthei** [comment]
> Yes indeed, the FBS schema is compiled with `flatc v. 1.12.0`, which produced the `zkinterface_generated.rs` file. And `flatc v. 2.0` is currently not compatible.
> 
> > I am on 2.0. I am also unable to regenerate the rust code with
> > `cargo build --features fbs`
> > The generated rust code does not compile and I get a lot of errors.
> 
FYI @sga001 's last message, this also does not work for flatc 1.11 with the same error.

> This is again because of incompatibilities between `flatc v 1.XX` and `flatc v. 2.XX`. Since the Rust code is constructed around what was generated from the `flatc` compiler, it cannot compile with something generated with incompatible versions.
> Maybe we should upgrade `zkinterface` at some point to migrate to `flatc 2.0`.
> 
> if I run
> 
> ```
> flatc -o outs zkinterface.fbs --json --strict-json -- examples/example.zkif
> ```
> 
> I get an error too. But the error says
> 
> ```
> flatc: error: binary "rust/example.zkif" does not have expected file_identifier "zkif", use --raw-binary to read this file anyway.
> ```
> 
> When adding this option, I get no error, but the output file is "empty". Only a single bracket pair `{}`, which is strange because no error means that the file is indeed compliant with the provided FBS schema.
> _NB_: in [Writing a Schema ](https://google.github.io/flatbuffers/flatbuffers_guide_writing_schema.html), it's said that
> 
> > Now, you can always prefix a FlatBuffer with your own file header, but FlatBuffers has a built-in way to add an identifier to a FlatBuffer that takes up minimal space, and keeps the buffer compatible with buffers that don't have such an identifier.
> 
> It means that this file identifier is not mandatory.
> 
> Regarding the fix suggested by @elefthei, this is actually true, but this is incomplete. All the types in `Message` should be updated this way (that is `Command`, `ConstraintSystem`, `CircuitHeader`, `Witness`), but even if I update all of these, this does not fill the JSON file properly...

Since we want to eliminate possible suspects, I updated all the correct files and filed a [PR](https://github.com/QED-it/zkinterface/pull/42). but still get the same error as you above. 

> I cannot tell for now if this is a bug on `zkinterface` or in `FlatBuffers/flatc`, and this requires more investigation. Maybe upgrading `zkinterface` to `flatc 2.0` would solve this issue?

While it would be a good general idea to update dependency versions, we have tried it with both `flatc 2.0` and `flatc 1.11` and it doesn't make a difference, we get the same error as you do. I have also tried a different flatbuffer library (specifically the Haskell one) and I am not able to read/write zkif files with that either. Right now the `zkif` CLI application is only compatible with itself, which defeats the purpose of using flatbuffer in the first place.

**Comment by elefthei** [comment]
If it is helpful, I wrote a zkif reader using only the generated rust files and this one seems to be compatible with other tools/languages.
[https://github.com/elefthei/spartan-zkinterface](https://github.com/elefthei/spartan-zkinterface)

In particular in `test` there are example files ex: `test/foo.zkif` and if you try reading it with flatc
`flatc -o outs schema/zkinterface.fbs --json --strict-json -- test/foo.zkif`

It works.

**Comment by Michael-Qedit** [comment]
Hi @elefthei ,

After a whole weekend clearing my mind, and only a 10-min investigation on this issue this morning, here is the solution you were waiting for.

> Right now the zkif CLI application is only compatible with itself, which defeats the purpose of using flatbuffer for sharing schema in the first place.

Actually, you are wrong. The purpose of zkInterface was to be interoperable, and yes it is. 
If you type
```
flatc --help
```
you get the list of all the available options for the `flatc` compiler. One is of particular interest:
```
--size-prefixed        Input binaries are size prefixed buffers.
```

Regarding your previous comment, it seems you have looked into the `zkinterface.fbs` file, which is good, but it seems you missed this [comment](https://github.com/QED-it/zkinterface/blob/master/zkinterface.fbs#L174) (admittedly, only a comment).
```
// All messages must be prefixed by the size of the message,
// not including the prefix, as a 4-bytes little-endian unsigned integer.
```

If you combine the knowledge brought by this comment, and the option grabbed from the CLI help of `flatc`, you get this:
```
$ flatc --size-prefixed -o outs zkinterface.fbs --json  -- rust/constraints.zkif 
$ cat outs/constraints.json 
{
  message_type: "ConstraintSystem",
  message: {
    constraints: [
      {
        linear_combination_a: {
          variable_ids: [
            1
          ],
          values: [
            1
          ]
        },
        linear_combination_b: {
          variable_ids: [
            1
          ],
          values: [
            1
          ]
        },
        linear_combination_c: {
          variable_ids: [
            4
          ],
          values: [
            1
          ]
        }
      },
      {
        linear_combination_a: {
          variable_ids: [
            2
          ],
          values: [
            1
          ]
        },
        linear_combination_b: {
          variable_ids: [
            2
          ],
          values: [
            1
          ]
        },
        linear_combination_c: {
          variable_ids: [
            5
          ],
          values: [
            1
          ]
        }
      },
      {
        linear_combination_a: {
          variable_ids: [
            0
          ],
          values: [
            1
          ]
        },
        linear_combination_b: {
          variable_ids: [
            4,
            5
          ],
          values: [
            1,
            1
          ]
        },
        linear_combination_c: {
          variable_ids: [
            3
          ],
          values: [
            1
          ]
        }
      }
    ]
  }
}
```
which is what was expected. 

> Would be great to get a solution soon.

Hopefully, right after the weekend is soon enough...

**Note**: There is a limitation in `flatc`, which reads only **one** `Message` type per file. In the `examples/example.zkif` file, we actually concatenate the three types into one only file (`Header`, `Witness`, `ConstraintSystem`). And if you run the previous command on it, it will only convert the first `Message` into JSON (in this case, only the `Header`) which is a pity... This limitation is overcome in `zkInterface` such that you can concatenate as many files as you want.

BTW, I will merge your PR soon. Thanks for that.
